vaadin.launch-browser=true
spring.application.name=proyectoJuegos

jwt.secret=7f2c8a9b4e6d1c3f8a0b7d5e9f1a2c4d6e8f0b1c3d5e7a9f2b4c6d8e0f1a3b5c
admin.secret=3f7d9a2c1b5e8f0d6a4c2e9b1d7f5a3c9e0b6d4f8a2c1e7b5d9f3a6c8e0b2d1

# Cambiar el puerto por defecto
server.port=8081

###############################################################################
# CONFIGURACI?N DE LA BASE DE DATOS (H2 en memoria)
###############################################################################
# Define la ubicaci?n de la BD. "mem:juegosdb" indica que vive en la RAM
spring.datasource.url=jdbc:h2:mem:juegosdb
# El conector necesario para que Java entienda el lenguaje de H2
spring.datasource.driverClassName=org.h2.Driver
# Credenciales por defecto para el acceso
spring.datasource.username=sa
spring.datasource.password=

###############################################################################
# CONFIGURACI?N DE JPA / HIBERNATE (Generaci?n de tablas)
###############################################################################
# 'update' analiza tus clases @Entity y crea/modifica las tablas autom?ticamente
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola de IntelliJ las sentencias SQL reales (CREATE, INSERT...)
spring.jpa.show-sql=true
# Formatea el SQL en la consola para que sea legible y no una l?nea infinita
spring.jpa.properties.hibernate.format_sql=true
# Indica a Hibernate que use el lenguaje espec?fico de H2 para las consultas
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

###############################################################################
# CONFIGURACI?N DE LA INTERFAZ WEB DE LA BASE DE DATOS
###############################################################################
# Activa la herramienta visual para ver las tablas desde el navegador
spring.h2.console.enabled=true
# Define la URL de acceso (ser?: http://localhost:8081/h2-console)
spring.h2.console.path=/h2-console
# Permite que la consola se vea correctamente dentro de marcos web (seguridad)
spring.h2.console.settings.web-allow-others=true
